# This is started by cirrus-run in the CI job "test:macos-aarch64".

arm_container:
  image: rust:1.70

# These are replaced by the CI job before cirrus-run. They are needed since
# environment variables aren't inherited from the GitLab CI.
env:
  CI_REPOSITORY_URL: "@CI_REPOSITORY_URL@"
  CI_COMMIT_REF_NAME: "@CI_COMMIT_REF_NAME@"

task:
  clone_script:
    - git clone --depth 1
                --recurse-submodules
                --shallow-submodules
                --branch "$CI_COMMIT_REF_NAME"
                "$CI_REPOSITORY_URL" .
  test_script:
    - cargo test --workspace
