[workspace]

members = [
    "spade-compiler",
    "spade-hir",
    "spade-types",
    "spade-common",
    "spade-parser",
    "spade-hir-codegen",
    "spade-typeinference",
    "spade-error-reporting",
    "spade-ast-lowering",
    "spade-builtins",
    "spade-testutil",
    "spade-tests",
    "parse_tree_macros"
]
