[workspace]

members = [
    "spade-compiler",
    "spade-hir",
    "spade-types",
    "spade-common",
    "spade-parser",
    "spade-typeinference",
    "spade-ast-lowering",
    "spade-testutil",
    "spade-tests",
    "spade-mir",
    "spade-hir-lowering",
    "spade-ast",
    "vcd-translate",
    "parse_tree_macros"
]

[patch.crates-io]
codespan = { git = "https://gitlab.com/spade-lang/codespan.git" }
codespan-reporting = { git = "https://gitlab.com/spade-lang/codespan.git" }
