[package]
name = "spade-python"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "spade"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module", "eyre"] }
spade = {path = "../spade-compiler"}
ron = "0.7.0"
color-eyre = "0.6.1"
logos = "0.11"
codespan-reporting = "0.12.0"

spade-common = {path = "../spade-common"}
spade-hir = {path = "../spade-hir"}
spade-ast = {path = "../spade-ast"}
spade-types = {path = "../spade-types"}
spade-parser = {path = "../spade-parser"}
spade-typeinference = {path = "../spade-typeinference"}
spade-hir-lowering = {path = "../spade-hir-lowering"}
spade-mir = {path = "../spade-mir"}
spade-ast-lowering = {path = "../spade-ast-lowering"}
vcd-translate = {path = "../vcd-translate"}
