[package]
name = "spade-typeinference"
version = "0.1.0"
authors = ["TheZoq2 <frans.skarman@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0"
thiserror = "1.0.20"

spade-common = {path = "../spade-common"}
spade-types = {path = "../spade-types"}
spade-hir = {path = "../spade-hir"}
parse_tree_macros = {path = "../parse_tree_macros"}

[dev-dependencies]
spade-testutil = {path = "../spade-testutil"}
