[package]
name = "spade-tests"
version = "0.1.0"
authors = ["TheZoq2 <frans.skarman@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
codespan-reporting = "0.11.0"
logos = "0.11"
colored = "2.0"
indoc = "1.0"

spade-common = {path = "../spade-common"}
spade-hir = {path = "../spade-hir"}
spade-mir = {path = "../spade-mir"}
spade-hir-lowering = {path = "../spade-hir-lowering"}
spade-typeinference = {path = "../spade-typeinference"}
parse_tree_macros = {path = "../parse_tree_macros"}

[dev-dependencies]
insta = "1.14.0"
unindent = "0.1.8"
