[package]
name = "spade"
version = "0.1.0"
authors = ["TheZoq2 <frans.skarman@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0"
logos = "0.11.4"
codespan = "0.12.0"
codespan-reporting = "0.12.0"
clap = { version = "3.1.18", features = ["derive"] }
serde = {version = "1.0.136", features = ["derive"]}

anyhow = "1.0.32"
thiserror = "1.0.20"

parse_tree_macros = {path = "../parse_tree_macros"}
indoc = "1.0"
ron = "0.7.0"

tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
tracing-tree = { git = "https://github.com/jonathanmorley/tracing-tree", rev = "8b97ec6e50e3f755644d1a0aaf4c45a2112607b2" }

spade-common = {path = "../spade-common"}
spade-hir = {path = "../spade-hir"}
spade-ast = {path = "../spade-ast"}
spade-types = {path = "../spade-types"}
spade-parser = {path = "../spade-parser"}
spade-typeinference = {path = "../spade-typeinference"}
spade-hir-lowering = {path = "../spade-hir-lowering"}
spade-mir = {path = "../spade-mir"}
spade-ast-lowering = {path = "../spade-ast-lowering"}


[dev-dependencies]
prettydiff = { version = "0.6.1", default-features = false }
pretty_assertions = "0.6"
