[package]
name = "spade-hir-lowering"
version = "0.1.0"
authors = ["TheZoq2 <frans.skarman@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
indoc = "1.0"
codespan = "0.11.1"
codespan-reporting = "0.11.1"

spade-common = {path = "../spade-common"}
spade-types = {path = "../spade-types"}
spade-hir = {path = "../spade-hir"}
spade-mir = {path = "../spade-mir"}
spade-typeinference = {path = "../spade-typeinference"}
parse_tree_macros = {path = "../parse_tree_macros"}

[dev-dependencies]
prettydiff = "0.3.1"
pretty_assertions = "0.6"
colored = "2.0"
spade-testutil = {path = "../spade-testutil"}
