[package]
name = "spade-mir"
version = "0.1.0"
authors = ["TheZoq2 <frans.skarman@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
logos = "0.11"
thiserror = "1.0"
codespan = "0.11.1"
codespan-reporting = "0.11.1"
indoc = "1.0.3"
nesty = "0.1"
itertools = "0.10.3"

spade-common = {path = "../spade-common"}
