[package]
name = "spade-hir"
version = "0.1.0"
authors = ["TheZoq2 <frans.skarman@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
spade-common = {path = "../spade-common"}
spade-types = {path = "../spade-types"}
thiserror = "1.0"
colored = "2.0"
